<a href="https://colab.research.google.com/github/cwf2/jeweled_style/blob/use_uva_common/Polyptoton_adj_window_sizes_no_repetitions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%pip install git+https://github.com/cwf2/uva_common

Collecting git+https://github.com/cwf2/uva_common
  Cloning https://github.com/cwf2/uva_common to /private/var/folders/2x/rfhzgyjn2zq2wlzk_kn4th680000gn/T/pip-req-build-wybr5emx
  Running command git clone --filter=blob:none --quiet https://github.com/cwf2/uva_common /private/var/folders/2x/rfhzgyjn2zq2wlzk_kn4th680000gn/T/pip-req-build-wybr5emx

  Resolved https://github.com/cwf2/uva_common to commit 09f4498e945d1eadd2429866b7a926f3d7e721b2

  Installing build dependencies ... -

 done

  Getting requirements to build wheel ... - done

  Preparing metadata (pyproject.toml) ... - done
Requirement already satisfied: lxml in ./venv/lib/python3.12/site-packages (from uva_common==0.1.0) (6.1.1)
Requirement already satisfied: pandas in ./venv/lib/python3.12/site-packages (from uva_common==0.1.0) (3.0.3)
Requirement already satisfied: gitpython in ./venv/lib/python3.12/site-packages (from uva_common==0.1.0) (3.1.50)
Requirement already satisfied: osfclient in ./venv/lib/python3.12/site-packages (from uva_common==0.1.0) (0.0.5)
Requirement already satisfied: gitdb<5,>=4.0.1 in ./venv/lib/python3.12/site-packages (from gitpython->uva_common==0.1.0) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in ./venv/lib/python3.12/site-packages (from gitdb<5,>=4.0.1->gitpython->uva_common==0.1.0) (5.0.3)
Requirement already satisfied: requests in ./venv/lib/python3.12/site-packages (from osfclient->uva_common==0.1.0) (2.34.2)
Requirement already satisfied: tqdm in ./venv/lib/python3.12/site-packages (from osfclient->uva_common==0.1.0) (4.68.3)
Requirement already satisfied: six in ./venv/lib/python3.12/site-packages (from osfclient->uva_common==0.1.0) (1.17.0)
Requirement already satisfied: numpy>=1.26.0 in ./venv/lib/python3.12/site-packages (from pandas->uva_common==0.1.0) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in ./venv/lib/python3.12/site-packages (from pandas->uva_common==0.1.0) (2.9.0.post0)
Requirement already satisfied: charset_normalizer<4,>=2 in ./venv/lib/python3.12/site-packages (from requests->osfclient->uva_common==0.1.0) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in ./venv/lib/python3.12/site-packages (from requests->osfclient->uva_common==0.1.0) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in ./venv/lib/python3.12/site-packages (from requests->osfclient->uva_common==0.1.0) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in ./venv/lib/python3.12/site-packages (from requests->osfclient->uva_common==0.1.0) (2026.6.17)

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: /Users/chris/Documents/git/dices-project-container/jeweled_style/venv/bin/python3.12 -m pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.

In [2]:
# utils
import os
import re
import json
import unicodedata as ud
import string

# for tokenized texts
import uva_common

# for analysis
import pandas as pd
import numpy as np

# for output
from IPython.display import HTML
import seaborn as sns
from matplotlib import pyplot as plt

In [3]:
# select text to analyze
#
# Iliad         tlg0012.tlg001.perseus-grc2
# Odyssey       tlg0012.tlg002.perseus-grc2
# Argonautica   tlg0001.tlg001.perseus-grc2
# Posthomerica  tlg2046.tlg001.perseus-grc2
# Dionysiaca    tlg2045.tlg001.perseus-grc2

urn = "tlg2046.tlg001.perseus-grc2"

In [4]:
# Download tokenized data
#  - for tokenization process see https://github.com/cwf2/uva_common

uva_common.download(f"{urn}.csv", node_id="tokens")

  0%|          | 0.00/11.0M [00:00<?, ?bytes/s]

  0%|          | 32.8k/11.0M [00:00<01:36, 113kbytes/s]

  0%|          | 49.2k/11.0M [00:00<01:33, 117kbytes/s]

  1%|          | 115k/11.0M [00:00<01:04, 168kbytes/s]

  2%|▏         | 262k/11.0M [00:00<00:27, 384kbytes/s]

  3%|▎         | 328k/11.0M [00:01<00:30, 351kbytes/s]

  4%|▍         | 426k/11.0M [00:01<00:29, 362kbytes/s]

  4%|▍         | 475k/11.0M [00:01<00:27, 383kbytes/s]

  5%|▌         | 557k/11.0M [00:01<00:23, 438kbytes/s]

  6%|▌         | 606k/11.0M [00:01<00:25, 409kbytes/s]

  6%|▌         | 655k/11.0M [00:02<00:32, 315kbytes/s]

  6%|▋         | 705k/11.0M [00:02<00:29, 345kbytes/s]

  7%|▋         | 770k/11.0M [00:02<00:26, 389kbytes/s]

  7%|▋         | 819k/11.0M [00:02<00:25, 394kbytes/s]

  8%|▊         | 868k/11.0M [00:02<00:24, 410kbytes/s]

  8%|▊         | 918k/11.0M [00:02<00:25, 400kbytes/s]

  9%|▉         | 967k/11.0M [00:02<00:35, 281kbytes/s]

  9%|▉         | 1.03M/11.0M [00:03<00:33, 300kbytes/s]

 10%|█         | 1.11M/11.0M [00:03<00:34, 288kbytes/s]

 11%|█         | 1.23M/11.0M [00:03<00:24, 399kbytes/s]

 12%|█▏        | 1.28M/11.0M [00:03<00:28, 336kbytes/s]

 12%|█▏        | 1.34M/11.0M [00:03<00:25, 372kbytes/s]

 13%|█▎        | 1.39M/11.0M [00:04<00:34, 279kbytes/s]

 14%|█▎        | 1.49M/11.0M [00:04<00:25, 368kbytes/s]

 14%|█▍        | 1.54M/11.0M [00:04<00:28, 332kbytes/s]

 15%|█▍        | 1.61M/11.0M [00:04<00:28, 326kbytes/s]

 15%|█▌        | 1.70M/11.0M [00:04<00:21, 436kbytes/s]

 16%|█▌        | 1.77M/11.0M [00:05<00:22, 418kbytes/s]

 17%|█▋        | 1.82M/11.0M [00:05<00:21, 424kbytes/s]

 17%|█▋        | 1.87M/11.0M [00:05<00:22, 407kbytes/s]

 17%|█▋        | 1.92M/11.0M [00:05<00:22, 411kbytes/s]

 18%|█▊        | 1.97M/11.0M [00:05<00:23, 388kbytes/s]

 18%|█▊        | 2.02M/11.0M [00:05<00:22, 396kbytes/s]

 19%|█▉        | 2.06M/11.0M [00:05<00:23, 382kbytes/s]

 19%|█▉        | 2.11M/11.0M [00:06<00:28, 316kbytes/s]

 20%|█▉        | 2.18M/11.0M [00:06<00:23, 380kbytes/s]

 20%|██        | 2.24M/11.0M [00:06<00:20, 425kbytes/s]

 21%|██        | 2.29M/11.0M [00:06<00:21, 414kbytes/s]

 21%|██▏       | 2.34M/11.0M [00:06<00:24, 354kbytes/s]

 22%|██▏       | 2.42M/11.0M [00:06<00:19, 443kbytes/s]

 22%|██▏       | 2.47M/11.0M [00:06<00:20, 424kbytes/s]

 23%|██▎       | 2.52M/11.0M [00:07<00:22, 373kbytes/s]

 23%|██▎       | 2.57M/11.0M [00:07<00:31, 270kbytes/s]

 24%|██▍       | 2.64M/11.0M [00:07<00:25, 327kbytes/s]

 24%|██▍       | 2.69M/11.0M [00:07<00:42, 197kbytes/s]

 25%|██▌       | 2.77M/11.0M [00:08<00:31, 265kbytes/s]

 26%|██▌       | 2.82M/11.0M [00:08<00:30, 264kbytes/s]

 26%|██▌       | 2.87M/11.0M [00:08<00:31, 256kbytes/s]

 26%|██▋       | 2.90M/11.0M [00:08<00:30, 263kbytes/s]

 27%|██▋       | 2.93M/11.0M [00:08<00:31, 259kbytes/s]

 27%|██▋       | 2.98M/11.0M [00:08<00:28, 277kbytes/s]

 27%|██▋       | 3.01M/11.0M [00:09<00:28, 278kbytes/s]

 28%|██▊       | 3.06M/11.0M [00:09<00:24, 322kbytes/s]

 28%|██▊       | 3.13M/11.0M [00:09<00:21, 359kbytes/s]

 29%|██▉       | 3.18M/11.0M [00:09<00:25, 308kbytes/s]

 30%|██▉       | 3.28M/11.0M [00:09<00:17, 437kbytes/s]

 30%|███       | 3.33M/11.0M [00:09<00:18, 410kbytes/s]

 31%|███       | 3.38M/11.0M [00:10<00:24, 307kbytes/s]

 31%|███▏      | 3.46M/11.0M [00:10<00:18, 398kbytes/s]

 32%|███▏      | 3.51M/11.0M [00:10<00:20, 364kbytes/s]

 32%|███▏      | 3.56M/11.0M [00:10<00:20, 357kbytes/s]

 33%|███▎      | 3.60M/11.0M [00:10<00:21, 344kbytes/s]

 33%|███▎      | 3.65M/11.0M [00:10<00:22, 328kbytes/s]

 34%|███▎      | 3.70M/11.0M [00:11<00:25, 284kbytes/s]

 34%|███▍      | 3.74M/11.0M [00:11<00:26, 274kbytes/s]

 35%|███▍      | 3.82M/11.0M [00:11<00:25, 282kbytes/s]

 35%|███▌      | 3.88M/11.0M [00:11<00:20, 341kbytes/s]

 36%|███▌      | 3.93M/11.0M [00:11<00:27, 253kbytes/s]

 36%|███▌      | 3.98M/11.0M [00:12<00:27, 259kbytes/s]

 37%|███▋      | 4.05M/11.0M [00:12<00:23, 301kbytes/s]

 37%|███▋      | 4.10M/11.0M [00:12<00:27, 252kbytes/s]

 38%|███▊      | 4.16M/11.0M [00:12<00:21, 316kbytes/s]

 38%|███▊      | 4.21M/11.0M [00:12<00:23, 288kbytes/s]

 39%|███▊      | 4.26M/11.0M [00:13<00:29, 225kbytes/s]

 39%|███▉      | 4.33M/11.0M [00:13<00:25, 260kbytes/s]

 40%|███▉      | 4.36M/11.0M [00:13<00:33, 199kbytes/s]

 40%|████      | 4.44M/11.0M [00:13<00:24, 267kbytes/s]

 41%|████      | 4.49M/11.0M [00:13<00:22, 293kbytes/s]

 41%|████▏     | 4.54M/11.0M [00:14<00:21, 307kbytes/s]

 42%|████▏     | 4.59M/11.0M [00:14<00:19, 324kbytes/s]

 42%|████▏     | 4.64M/11.0M [00:14<00:18, 342kbytes/s]

 43%|████▎     | 4.69M/11.0M [00:14<00:24, 263kbytes/s]

 43%|████▎     | 4.72M/11.0M [00:14<00:24, 259kbytes/s]

 43%|████▎     | 4.78M/11.0M [00:14<00:19, 326kbytes/s]

 44%|████▍     | 4.83M/11.0M [00:15<00:26, 234kbytes/s]

 45%|████▍     | 4.90M/11.0M [00:15<00:20, 297kbytes/s]

 45%|████▍     | 4.95M/11.0M [00:15<00:20, 298kbytes/s]

 45%|████▌     | 5.00M/11.0M [00:15<00:18, 321kbytes/s]

 46%|████▌     | 5.05M/11.0M [00:15<00:20, 293kbytes/s]

 46%|████▋     | 5.10M/11.0M [00:15<00:20, 292kbytes/s]

 47%|████▋     | 5.18M/11.0M [00:16<00:15, 383kbytes/s]

 48%|████▊     | 5.23M/11.0M [00:16<00:16, 351kbytes/s]

 48%|████▊     | 5.28M/11.0M [00:16<00:16, 344kbytes/s]

 48%|████▊     | 5.32M/11.0M [00:16<00:16, 341kbytes/s]

 49%|████▉     | 5.37M/11.0M [00:16<00:17, 319kbytes/s]

 49%|████▉     | 5.42M/11.0M [00:16<00:16, 341kbytes/s]

 50%|████▉     | 5.47M/11.0M [00:17<00:15, 355kbytes/s]

 50%|█████     | 5.54M/11.0M [00:17<00:14, 384kbytes/s]

 51%|█████     | 5.60M/11.0M [00:17<00:12, 426kbytes/s]

 52%|█████▏    | 5.67M/11.0M [00:17<00:14, 364kbytes/s]

 53%|█████▎    | 5.78M/11.0M [00:17<00:10, 507kbytes/s]

 53%|█████▎    | 5.85M/11.0M [00:17<00:10, 512kbytes/s]

 54%|█████▍    | 5.91M/11.0M [00:17<00:11, 462kbytes/s]

 55%|█████▍    | 6.00M/11.0M [00:18<00:09, 539kbytes/s]

 55%|█████▌    | 6.06M/11.0M [00:18<00:09, 524kbytes/s]

 56%|█████▌    | 6.13M/11.0M [00:18<00:09, 525kbytes/s]

 56%|█████▋    | 6.19M/11.0M [00:18<00:09, 529kbytes/s]

 57%|█████▋    | 6.26M/11.0M [00:18<00:09, 485kbytes/s]

 57%|█████▋    | 6.32M/11.0M [00:18<00:09, 500kbytes/s]

 58%|█████▊    | 6.39M/11.0M [00:18<00:10, 437kbytes/s]

 59%|█████▉    | 6.47M/11.0M [00:18<00:08, 520kbytes/s]

 59%|█████▉    | 6.54M/11.0M [00:19<00:10, 417kbytes/s]

 60%|█████▉    | 6.59M/11.0M [00:19<00:11, 395kbytes/s]

 61%|██████    | 6.68M/11.0M [00:19<00:08, 493kbytes/s]

 61%|██████▏   | 6.75M/11.0M [00:19<00:12, 353kbytes/s]

 62%|██████▏   | 6.82M/11.0M [00:20<00:11, 353kbytes/s]

 63%|██████▎   | 6.88M/11.0M [00:20<00:12, 321kbytes/s]

 63%|██████▎   | 6.96M/11.0M [00:20<00:10, 380kbytes/s]

 64%|██████▎   | 7.01M/11.0M [00:20<00:10, 375kbytes/s]

 64%|██████▍   | 7.06M/11.0M [00:20<00:10, 369kbytes/s]

 65%|██████▍   | 7.11M/11.0M [00:20<00:10, 387kbytes/s]

 65%|██████▌   | 7.16M/11.0M [00:20<00:09, 387kbytes/s]

 66%|██████▌   | 7.21M/11.0M [00:21<00:11, 335kbytes/s]

 66%|██████▋   | 7.31M/11.0M [00:21<00:07, 466kbytes/s]

 67%|██████▋   | 7.37M/11.0M [00:21<00:08, 414kbytes/s]

 67%|██████▋   | 7.42M/11.0M [00:21<00:08, 417kbytes/s]

 68%|██████▊   | 7.47M/11.0M [00:21<00:09, 361kbytes/s]

 68%|██████▊   | 7.52M/11.0M [00:21<00:11, 296kbytes/s]

 69%|██████▉   | 7.57M/11.0M [00:22<00:10, 330kbytes/s]

 69%|██████▉   | 7.63M/11.0M [00:22<00:09, 373kbytes/s]

 70%|██████▉   | 7.68M/11.0M [00:22<00:08, 397kbytes/s]

 70%|███████   | 7.73M/11.0M [00:22<00:08, 403kbytes/s]

 71%|███████   | 7.78M/11.0M [00:22<00:08, 385kbytes/s]

 71%|███████   | 7.83M/11.0M [00:22<00:08, 385kbytes/s]

 72%|███████▏  | 7.88M/11.0M [00:22<00:07, 398kbytes/s]

 72%|███████▏  | 7.93M/11.0M [00:23<00:09, 326kbytes/s]

 73%|███████▎  | 8.00M/11.0M [00:23<00:09, 313kbytes/s]

 74%|███████▎  | 8.09M/11.0M [00:23<00:09, 315kbytes/s]

 74%|███████▍  | 8.18M/11.0M [00:23<00:07, 395kbytes/s]

 75%|███████▍  | 8.22M/11.0M [00:23<00:07, 366kbytes/s]

 75%|███████▌  | 8.27M/11.0M [00:23<00:07, 366kbytes/s]

 76%|███████▌  | 8.32M/11.0M [00:24<00:07, 336kbytes/s]

 76%|███████▌  | 8.37M/11.0M [00:24<00:07, 334kbytes/s]

 77%|███████▋  | 8.42M/11.0M [00:24<00:10, 241kbytes/s]

 78%|███████▊  | 8.55M/11.0M [00:24<00:06, 393kbytes/s]

 78%|███████▊  | 8.62M/11.0M [00:25<00:07, 320kbytes/s]

 79%|███████▉  | 8.72M/11.0M [00:25<00:05, 420kbytes/s]

 80%|███████▉  | 8.78M/11.0M [00:25<00:05, 397kbytes/s]

 80%|████████  | 8.85M/11.0M [00:25<00:05, 393kbytes/s]

 81%|████████  | 8.90M/11.0M [00:25<00:05, 408kbytes/s]

 81%|████████▏ | 8.95M/11.0M [00:25<00:05, 411kbytes/s]

 82%|████████▏ | 8.99M/11.0M [00:25<00:04, 422kbytes/s]

 82%|████████▏ | 9.06M/11.0M [00:26<00:04, 452kbytes/s]

 83%|████████▎ | 9.13M/11.0M [00:26<00:03, 478kbytes/s]

 84%|████████▎ | 9.19M/11.0M [00:26<00:03, 485kbytes/s]

 84%|████████▍ | 9.27M/11.0M [00:26<00:03, 546kbytes/s]

 85%|████████▌ | 9.36M/11.0M [00:26<00:02, 594kbytes/s]

 86%|████████▌ | 9.42M/11.0M [00:26<00:03, 511kbytes/s]

 87%|████████▋ | 9.55M/11.0M [00:26<00:02, 690kbytes/s]

 88%|████████▊ | 9.63M/11.0M [00:26<00:02, 653kbytes/s]

 88%|████████▊ | 9.72M/11.0M [00:27<00:02, 628kbytes/s]

 89%|████████▉ | 9.80M/11.0M [00:27<00:02, 502kbytes/s]

 90%|█████████ | 9.95M/11.0M [00:27<00:01, 687kbytes/s]

 91%|█████████ | 10.0M/11.0M [00:27<00:01, 622kbytes/s]

 92%|█████████▏| 10.1M/11.0M [00:27<00:01, 594kbytes/s]

 93%|█████████▎| 10.2M/11.0M [00:27<00:01, 610kbytes/s]

 93%|█████████▎| 10.3M/11.0M [00:27<00:01, 612kbytes/s]

 94%|█████████▍| 10.3M/11.0M [00:28<00:01, 619kbytes/s]

 94%|█████████▍| 10.4M/11.0M [00:28<00:01, 612kbytes/s]

 95%|█████████▌| 10.5M/11.0M [00:28<00:00, 589kbytes/s]

 96%|█████████▌| 10.5M/11.0M [00:28<00:00, 606kbytes/s]

 96%|█████████▋| 10.6M/11.0M [00:28<00:00, 670kbytes/s]

 97%|█████████▋| 10.7M/11.0M [00:28<00:00, 591kbytes/s]

 98%|█████████▊| 10.8M/11.0M [00:28<00:00, 586kbytes/s]

 99%|█████████▊| 10.8M/11.0M [00:28<00:00, 613kbytes/s]

 99%|█████████▉| 10.9M/11.0M [00:29<00:00, 623kbytes/s]

100%|█████████▉| 11.0M/11.0M [00:29<00:00, 610kbytes/s]

100%|██████████| 11.0M/11.0M [00:29<00:00, 377kbytes/s]

In [5]:
# load downloaded tokens into a Pandas DataFrame
path = os.path.join("data", f"{urn}.csv")
tokens = pd.read_csv(path)
display(tokens)

,author,title,work,urn,line_id,text,lemma,pos,verbform,mood,...,case,gender,speech_id,speaker,addressee,level,type,cluster,turn,tags
0,Quintus Smyrnaeus,τὰ μεθ᾿ Ὅμηρον,Posthomerica,urn:cts:greekLit:tlg2046.tlg001.perseus-grc2:1.1,01_0001,Εὖθ’,εὖτε,ADV,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
1,Quintus Smyrnaeus,τὰ μεθ᾿ Ὅμηρον,Posthomerica,urn:cts:greekLit:tlg2046.tlg001.perseus-grc2:1.1,01_0001,ὑπὸ,ὑπό,ADP,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
2,Quintus Smyrnaeus,τὰ μεθ᾿ Ὅμηρον,Posthomerica,urn:cts:greekLit:tlg2046.tlg001.perseus-grc2:1.1,01_0001,Πηλείωνι,Πηλεύς,NOUN,NaN,NaN,...,Dat,Masc,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
3,Quintus Smyrnaeus,τὰ μεθ᾿ Ὅμηρον,Posthomerica,urn:cts:greekLit:tlg2046.tlg001.perseus-grc2:1.1,01_0001,δάμη,δαμάζω,VERB,Fin,Ind,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
4,Quintus Smyrnaeus,τὰ μεθ᾿ Ὅμηρον,Posthomerica,urn:cts:greekLit:tlg2046.tlg001.perseus-grc2:1.1,01_0001,θεοείκελος,θεοείκελος,ADJ,NaN,NaN,...,Nom,Masc,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60175,Quintus Smyrnaeus,τὰ μεθ᾿ Ὅμηρον,Posthomerica,urn:cts:greekLit:tlg2046.tlg001.perseus-grc2:1...,14_0658,ὑπὲρ,ὑπέρ,ADP,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
60176,Quintus Smyrnaeus,τὰ μεθ᾿ Ὅμηρον,Posthomerica,urn:cts:greekLit:tlg2046.tlg001.perseus-grc2:1...,14_0658,πόντοιο,πόντος,NOUN,NaN,NaN,...,Gen,Masc,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
60177,Quintus Smyrnaeus,τὰ μεθ᾿ Ὅμηρον,Posthomerica,urn:cts:greekLit:tlg2046.tlg001.perseus-grc2:1...,14_0658,λυγρὰς,λυγρός,ADJ,NaN,NaN,...,Acc,Fem,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
60178,Quintus Smyrnaeus,τὰ μεθ᾿ Ὅμηρον,Posthomerica,urn:cts:greekLit:tlg2046.tlg001.perseus-grc2:1...,14_0658,ὑπάλυξαν,ὑπαλύσκω,VERB,Fin,Ind,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
60179,Quintus Smyrnaeus,τὰ μεθ᾿ Ὅμηρον,Posthomerica,urn:cts:greekLit:tlg2046.tlg001.perseus-grc2:1...,14_0658,ἀέλλας,ἄελλα,NOUN,NaN,NaN,...,Acc,Fem,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN

In [6]:
# minor changes to make table match Lotte's columns
tokens = tokens.rename(columns={"text": "token"})
tokens[["book", "line"]] = pd.DataFrame(tokens["line_id"].str.split("_").tolist())
tokens["book"] = tokens["book"].str.lstrip("0")
tokens["line"] = tokens["line"].str.lstrip("0")

What needs to happen?

- Divide the tokens into lists of five
- Each token is the first of a new set of five (so 1-5, 2-6, 3-7 etc.)
- Keep each token's id, book and line number (maybe change id into 00_001a and so on?)

In [7]:
# set window size
window_size = 7

# create new list to hold windows
n_tokens = []
# remember last line to increment window id suffix
last_line_id = None

for i in range(len(tokens) - (window_size - 1)): # Ensure there are at least n tokens to form a sequence

    # copy next window_size lines from the table
    this_window = tokens.iloc[i:i+window_size][["book", "line", "token", "lemma", "pos"]]
    
    # assign window id
    line_id = tokens.iloc[i]["line_id"]
    if line_id != last_line_id:
        suffix_counter = 0
        last_line_id = line_id  # fixed: without this, suffix_counter never
                                 # advances past 0, so window_id collapses
                                 # every window starting on the same line
                                 # into one id
    suffix_letter = string.ascii_lowercase[suffix_counter]
    this_window.insert(0, "window_id", line_id + suffix_letter)

    # add this window to growing list
    n_tokens.append(this_window)
    suffix_counter += 1  # fixed: was never incremented, so this always
                          # stayed "a"

# concatenate as a single data frame
n_tokens = pd.concat(n_tokens)

# add combined lemma-pos column
n_tokens["lemma_pos"] = n_tokens[["lemma", "pos"]].apply(tuple, axis=1)

In [8]:
# ### Lotte's original code
# window_size = 7

# all_tokens_data = []
# for index, row in lines.iterrows():
#     for token in row['tokens']:
#         all_tokens_data.append({
#             'token_obj': token,
#             'original_line_id': row['id'],
#             'original_line_book': row['book'],
#             'original_line_line': row['line']
#         })

# # Now create the 5-token sequences
# n_token_sequences = []
# for i in range(len(all_tokens_data) - (window_size - 1)): # Ensure there are at least 5 tokens to form a sequence
#     # Get the 5 token objects
#     sequence_tokens = [all_tokens_data[j]['token_obj'] for j in range(i, i + window_size)]

#     # Get the metadata (id, book, line) from the first token in the sequence
#     first_token_metadata = all_tokens_data[i]

#     n_token_sequences.append({
#         'id': first_token_metadata['original_line_id'],
#         'book': first_token_metadata['original_line_book'],
#         'line': first_token_metadata['original_line_line'],
#         'n_tokens': sequence_tokens
#     })

# # Convert to DataFrame for easier handling and display
# n_token_df = pd.DataFrame(n_token_sequences)

# # Add an alphabetical suffix to the 'id' column
# import string

# new_ids = []
# current_id = None
# suffix_counter = 0

# for index, row in n_token_df.iterrows():
#     if row['id'] != current_id:
#         current_id = row['id']
#         suffix_counter = 0

#     suffix_letter = string.ascii_lowercase[suffix_counter]
#     new_id = f"{row['id']}{suffix_letter}"
#     new_ids.append(new_id)

#     suffix_counter += 1

# n_token_df['id'] = new_ids

# print(f"Created {len(n_token_df)} six-token sequences with unique IDs.")
# display(n_token_df.head())

Next cell: change so that each row is one token from a set of five, e.g. 00_001a

In [9]:
# # start with an empty list of rows
# rows = []

# # iterate over speeches
# for line in n_token_df.itertuples():   # lines

#     # iterate over tokens
#     for token in line.n_tokens:   # tokens

#         # create a record for this token
#         row = {
#             "window_id": line.id,
#             "book": line.book,
#             "line": line.line,
#             "token": token.text,        #token.text
#             "lemma": token.lemma_,
#             "pos": token.pos_,
#             "lemma_pos": (token.lemma_, token.pos_)
#         }

#         # add row to the list of rows
#         rows.append(row)

# # convert to a table
# n_tokens = pd.DataFrame(rows)   # tokens

# display(n_tokens[0:40])  # tokens

In [10]:
from collections import Counter

In [11]:
results = []

pos_mask = n_tokens['pos'].isin(['ADJ', 'NOUN', 'NUM', 'PROPN', 'VERB'])

excluded_lemmas = ["ἀλλ'", "'ἀλλʼ", "ἀλλά", "ἀλλὰ", "ἀτάρ", "ἀτὰρ", "αὐτάρ", "αὐτὰρ", "ἤ", "ἢ", "ἠέ", "ἠὲ", "ἦε", "ἦέ", "ἠδ'", "ἠδʼ" "ἠδέ", "ἠδὲ", "ἤτ'", "ἤτʼ", "ἤτε", "ἤτοι", "μηδ'", "μηδʼ", "μηδέ", "μηδὲ", "μήθ'", "μήτ'", "μήτʼ", "μήτε", "μήτέ", "οὐδ'", "οὐδʼ", "οὐδέ", "οὐδὲ", "οὔθ'", "οὔθʼ", "οὔτ'", "οὔτʼ", "οὔτε", "οὔτέ", "ἀρ'", "ἀρʼ", "ἄρ'", "ἄρʼ", "ἂρ'", "ἂρʼ", "ἄρα", "ἄρά", "ῥ'", "ῥʼ", "ῥα", "ῥά", "αὖ", "γ'", "γʼ", "γε", "γέ", "γάρ", "γὰρ", "δαὶ", "δ'", "δʼ", "δέ", "δὲ", "θην", "θήν", "κε", "κέ", "κεν", "κέν", "χ'", "χʼ", "κ'", "κʼ", "μάν", "μὰν", "μέν", "μὲν", "μήν", "μὴν", "νυ", "νύ", "νυν", "περ", "πέρ", "μὰ", "καί", "καὶ", "μή", "μὴ", "οὐ", "οὐκ", "οὐχ", "οὔ", "οὖν", "ὦ", "ὤ", "ὢ", "που", "πού", "τὰρ", "τε", "τέ", "τ'", "τʼ", "θ'", "θʼ", "ἂν", "ἄν", "δή", "δὴ", "τοιγὰρ", "αἴ", "αἲ", "αἴθ'", "αἴθʼ", "αἴθε", "εἰ", "εἴ", "εἴθ'",  "εἴθʼ", "ἐπεί", "ἐπεὶ", "ἐπειδὰν", "ἐπειδὴ", "ἐπήν", "ἐπὴν", "εὖθ'", "εὖθʼ", "εὖτ'", "εὖτʼ", "εὖτε", "εὖτέ", "ἠύτ'", "ἠύτʼ", "ἠΰτ'", "ἠΰτʼ", "ἠΰτε", "ἦμος", "ἡνίκ", "ἵν'", "ἵνʼ", "ἵνα", "ἵνά", "ἤν", "ἢν", "ὅτ'", "ὅτʼ", "ὅτε", "ὡς", "ὥστ'", "ὥστʼ", "ὥστε", "ὅππως", "ὅπως", "εἷος", "εἷός", "ἕως", "ἧος", "ἧός", "ὄφρ'", "ὄφρʼ", "ὄφρα", "ὄφρά", "πρίν", "πρὶν", "ὁ", "ὅς"]

lexicon_mask = ~n_tokens['lemma'].isin(excluded_lemmas)

combined_mask = pos_mask & lexicon_mask

lemmas_by_window = n_tokens.loc[combined_mask].groupby('window_id').agg(
    book = ('book', 'first'),
    line = ('line', 'first'),
    lemmas = ('lemma', list),
    tokens = ('token', list),
    pos = ('pos', list),
    lemma_pos = ('lemma_pos', list)
    ).reset_index()

display(lemmas_by_window)

,window_id,book,line,lemmas,tokens,pos,lemma_pos
0,01_0001a,1,1,"[Πηλεύς, δαμάζω, θεοείκελος, Ἕκτωρ]","[Πηλείωνι, δάμη, θεοείκελος, Ἕκτωρ]","[NOUN, VERB, ADJ, NOUN]","[(Πηλεύς, NOUN), (δαμάζω, VERB), (θεοείκελος, ..."
1,01_0001b,1,1,"[Πηλεύς, δαμάζω, θεοείκελος, Ἕκτωρ]","[Πηλείωνι, δάμη, θεοείκελος, Ἕκτωρ]","[NOUN, VERB, ADJ, NOUN]","[(Πηλεύς, NOUN), (δαμάζω, VERB), (θεοείκελος, ..."
2,01_0001c,1,1,"[Πηλεύς, δαμάζω, θεοείκελος, Ἕκτωρ, πυρή]","[Πηλείωνι, δάμη, θεοείκελος, Ἕκτωρ, πυρὴ]","[NOUN, VERB, ADJ, NOUN, NOUN]","[(Πηλεύς, NOUN), (δαμάζω, VERB), (θεοείκελος, ..."
3,01_0001d,1,1,"[δαμάζω, θεοείκελος, Ἕκτωρ, πυρή, καταδάπτω]","[δάμη, θεοείκελος, Ἕκτωρ, πυρὴ, κατέδαψε]","[VERB, ADJ, NOUN, NOUN, VERB]","[(δαμάζω, VERB), (θεοείκελος, ADJ), (Ἕκτωρ, NO..."
4,01_0001e,1,1,"[θεοείκελος, Ἕκτωρ, πυρή, καταδάπτω]","[θεοείκελος, Ἕκτωρ, πυρὴ, κατέδαψε]","[ADJ, NOUN, NOUN, VERB]","[(θεοείκελος, ADJ), (Ἕκτωρ, NOUN), (πυρή, NOUN..."
...,...,...,...,...,...,...,...
60156,14_0657d,14,657,"[ἱκάνω, ὅπῃ, θεός, ἄγω, ἕκαστος, ὅσος]","[ἵκανεν, ὅπῃ, θεὸς, ἦγεν, ἕκαστον, ὅσσοι]","[VERB, ADJ, NOUN, VERB, ADJ, ADJ]","[(ἱκάνω, VERB), (ὅπῃ, ADJ), (θεός, NOUN), (ἄγω..."
60157,14_0657e,14,657,"[ὅπῃ, θεός, ἄγω, ἕκαστος, ὅσος, πόντος]","[ὅπῃ, θεὸς, ἦγεν, ἕκαστον, ὅσσοι, πόντοιο]","[ADJ, NOUN, VERB, ADJ, ADJ, NOUN]","[(ὅπῃ, ADJ), (θεός, NOUN), (ἄγω, VERB), (ἕκαστ..."
60158,14_0657f,14,657,"[θεός, ἄγω, ἕκαστος, ὅσος, πόντος, λυγρός]","[θεὸς, ἦγεν, ἕκαστον, ὅσσοι, πόντοιο, λυγρὰς]","[NOUN, VERB, ADJ, ADJ, NOUN, ADJ]","[(θεός, NOUN), (ἄγω, VERB), (ἕκαστος, ADJ), (ὅ..."
60159,14_0657g,14,657,"[ἄγω, ἕκαστος, ὅσος, πόντος, λυγρός, ὑπαλύσκω]","[ἦγεν, ἕκαστον, ὅσσοι, πόντοιο, λυγρὰς, ὑπάλυξαν]","[VERB, ADJ, ADJ, NOUN, ADJ, VERB]","[(ἄγω, VERB), (ἕκαστος, ADJ), (ὅσος, ADJ), (πό..."
60160,14_0657h,14,657,"[ἕκαστος, ὅσος, πόντος, λυγρός, ὑπαλύσκω, ἄελλα]","[ἕκαστον, ὅσσοι, πόντοιο, λυγρὰς, ὑπάλυξαν, ἀέ...","[ADJ, ADJ, NOUN, ADJ, VERB, NOUN]","[(ἕκαστος, ADJ), (ὅσος, ADJ), (πόντος, NOUN), ..."

In [12]:
# lemmas_by_window is already one row per window_id (see previous cell), so
# there's nothing left to group/sum here — the original re-groupby crashed
# with "TypeError: unsupported operand type(s) for +: 'int' and 'list'"
# because bare `sum` starts its accumulator at 0, which can't be added to a
# single-row group's list value. Kept as a plain copy instead.
results = lemmas_by_window.copy()
results["wc"] = results["lemma_pos"].apply(Counter)
results

,window_id,book,line,lemmas,tokens,pos,lemma_pos,wc
0,01_0001a,1,1,"[Πηλεύς, δαμάζω, θεοείκελος, Ἕκτωρ]","[Πηλείωνι, δάμη, θεοείκελος, Ἕκτωρ]","[NOUN, VERB, ADJ, NOUN]","[(Πηλεύς, NOUN), (δαμάζω, VERB), (θεοείκελος, ...","{('Πηλεύς', 'NOUN'): 1, ('δαμάζω', 'VERB'): 1,..."
1,01_0001b,1,1,"[Πηλεύς, δαμάζω, θεοείκελος, Ἕκτωρ]","[Πηλείωνι, δάμη, θεοείκελος, Ἕκτωρ]","[NOUN, VERB, ADJ, NOUN]","[(Πηλεύς, NOUN), (δαμάζω, VERB), (θεοείκελος, ...","{('Πηλεύς', 'NOUN'): 1, ('δαμάζω', 'VERB'): 1,..."
2,01_0001c,1,1,"[Πηλεύς, δαμάζω, θεοείκελος, Ἕκτωρ, πυρή]","[Πηλείωνι, δάμη, θεοείκελος, Ἕκτωρ, πυρὴ]","[NOUN, VERB, ADJ, NOUN, NOUN]","[(Πηλεύς, NOUN), (δαμάζω, VERB), (θεοείκελος, ...","{('Πηλεύς', 'NOUN'): 1, ('δαμάζω', 'VERB'): 1,..."
3,01_0001d,1,1,"[δαμάζω, θεοείκελος, Ἕκτωρ, πυρή, καταδάπτω]","[δάμη, θεοείκελος, Ἕκτωρ, πυρὴ, κατέδαψε]","[VERB, ADJ, NOUN, NOUN, VERB]","[(δαμάζω, VERB), (θεοείκελος, ADJ), (Ἕκτωρ, NO...","{('δαμάζω', 'VERB'): 1, ('θεοείκελος', 'ADJ'):..."
4,01_0001e,1,1,"[θεοείκελος, Ἕκτωρ, πυρή, καταδάπτω]","[θεοείκελος, Ἕκτωρ, πυρὴ, κατέδαψε]","[ADJ, NOUN, NOUN, VERB]","[(θεοείκελος, ADJ), (Ἕκτωρ, NOUN), (πυρή, NOUN...","{('θεοείκελος', 'ADJ'): 1, ('Ἕκτωρ', 'NOUN'): ..."
...,...,...,...,...,...,...,...,...
60156,14_0657d,14,657,"[ἱκάνω, ὅπῃ, θεός, ἄγω, ἕκαστος, ὅσος]","[ἵκανεν, ὅπῃ, θεὸς, ἦγεν, ἕκαστον, ὅσσοι]","[VERB, ADJ, NOUN, VERB, ADJ, ADJ]","[(ἱκάνω, VERB), (ὅπῃ, ADJ), (θεός, NOUN), (ἄγω...","{('ἱκάνω', 'VERB'): 1, ('ὅπῃ', 'ADJ'): 1, ('θε..."
60157,14_0657e,14,657,"[ὅπῃ, θεός, ἄγω, ἕκαστος, ὅσος, πόντος]","[ὅπῃ, θεὸς, ἦγεν, ἕκαστον, ὅσσοι, πόντοιο]","[ADJ, NOUN, VERB, ADJ, ADJ, NOUN]","[(ὅπῃ, ADJ), (θεός, NOUN), (ἄγω, VERB), (ἕκαστ...","{('ὅπῃ', 'ADJ'): 1, ('θεός', 'NOUN'): 1, ('ἄγω..."
60158,14_0657f,14,657,"[θεός, ἄγω, ἕκαστος, ὅσος, πόντος, λυγρός]","[θεὸς, ἦγεν, ἕκαστον, ὅσσοι, πόντοιο, λυγρὰς]","[NOUN, VERB, ADJ, ADJ, NOUN, ADJ]","[(θεός, NOUN), (ἄγω, VERB), (ἕκαστος, ADJ), (ὅ...","{('θεός', 'NOUN'): 1, ('ἄγω', 'VERB'): 1, ('ἕκ..."
60159,14_0657g,14,657,"[ἄγω, ἕκαστος, ὅσος, πόντος, λυγρός, ὑπαλύσκω]","[ἦγεν, ἕκαστον, ὅσσοι, πόντοιο, λυγρὰς, ὑπάλυξαν]","[VERB, ADJ, ADJ, NOUN, ADJ, VERB]","[(ἄγω, VERB), (ἕκαστος, ADJ), (ὅσος, ADJ), (πό...","{('ἄγω', 'VERB'): 1, ('ἕκαστος', 'ADJ'): 1, ('..."
60160,14_0657h,14,657,"[ἕκαστος, ὅσος, πόντος, λυγρός, ὑπαλύσκω, ἄελλα]","[ἕκαστον, ὅσσοι, πόντοιο, λυγρὰς, ὑπάλυξαν, ἀέ...","[ADJ, ADJ, NOUN, ADJ, VERB, NOUN]","[(ἕκαστος, ADJ), (ὅσος, ADJ), (πόντος, NOUN), ...","{('ἕκαστος', 'ADJ'): 1, ('ὅσος', 'ADJ'): 1, ('..."

In [13]:
results_limited = results.drop(columns = ['lemmas', 'pos', 'lemma_pos'])

results_limited

,window_id,book,line,tokens,wc
0,01_0001a,1,1,"[Πηλείωνι, δάμη, θεοείκελος, Ἕκτωρ]","{('Πηλεύς', 'NOUN'): 1, ('δαμάζω', 'VERB'): 1,..."
1,01_0001b,1,1,"[Πηλείωνι, δάμη, θεοείκελος, Ἕκτωρ]","{('Πηλεύς', 'NOUN'): 1, ('δαμάζω', 'VERB'): 1,..."
2,01_0001c,1,1,"[Πηλείωνι, δάμη, θεοείκελος, Ἕκτωρ, πυρὴ]","{('Πηλεύς', 'NOUN'): 1, ('δαμάζω', 'VERB'): 1,..."
3,01_0001d,1,1,"[δάμη, θεοείκελος, Ἕκτωρ, πυρὴ, κατέδαψε]","{('δαμάζω', 'VERB'): 1, ('θεοείκελος', 'ADJ'):..."
4,01_0001e,1,1,"[θεοείκελος, Ἕκτωρ, πυρὴ, κατέδαψε]","{('θεοείκελος', 'ADJ'): 1, ('Ἕκτωρ', 'NOUN'): ..."
...,...,...,...,...,...
60156,14_0657d,14,657,"[ἵκανεν, ὅπῃ, θεὸς, ἦγεν, ἕκαστον, ὅσσοι]","{('ἱκάνω', 'VERB'): 1, ('ὅπῃ', 'ADJ'): 1, ('θε..."
60157,14_0657e,14,657,"[ὅπῃ, θεὸς, ἦγεν, ἕκαστον, ὅσσοι, πόντοιο]","{('ὅπῃ', 'ADJ'): 1, ('θεός', 'NOUN'): 1, ('ἄγω..."
60158,14_0657f,14,657,"[θεὸς, ἦγεν, ἕκαστον, ὅσσοι, πόντοιο, λυγρὰς]","{('θεός', 'NOUN'): 1, ('ἄγω', 'VERB'): 1, ('ἕκ..."
60159,14_0657g,14,657,"[ἦγεν, ἕκαστον, ὅσσοι, πόντοιο, λυγρὰς, ὑπάλυξαν]","{('ἄγω', 'VERB'): 1, ('ἕκαστος', 'ADJ'): 1, ('..."
60160,14_0657h,14,657,"[ἕκαστον, ὅσσοι, πόντοιο, λυγρὰς, ὑπάλυξαν, ἀέ...","{('ἕκαστος', 'ADJ'): 1, ('ὅσος', 'ADJ'): 1, ('..."

In [14]:
# Identify repeated lemmas (appear at least twice)
results_limited['repeated_lemma'] = results_limited['wc'].apply(                                  # apply a lambda function to the data in wc in results
    lambda c: [lemma for lemma, count in c.items() if count >= 2]                  # a lambda function is an anonymous function, c is the Count object from wc
                                                                                   # If the count in the items (the lemma: count pairs in wc) is two or higher, keep the lemma
)

# Keep couplets where there is at least one such lemma
filtered_results = results_limited[results_limited['repeated_lemma'].apply(len) >= 1].copy()            # from the results, keep only the lines that have one or more from the list of repeated_lemmas

# Create a new DataFrame with one row per repeated lemma
expanded_results = filtered_results.explode('repeated_lemma')

# Extract lemma and pos from the tuple in 'repeated_lemma'
expanded_results['rep_lemma'] = expanded_results['repeated_lemma'].apply(lambda x: x[0])
expanded_results['rep_pos'] = expanded_results['repeated_lemma'].apply(lambda x: x[1])

# Drop the original 'repeated_lemma' column and other intermediate columns
expanded_results = expanded_results.drop(columns=['repeated_lemma'])

# Display the results
display(expanded_results)

,window_id,book,line,tokens,wc,rep_lemma,rep_pos
207,01_0033c,1,33,"[ἄλλαι, ἕποντο, δυώδεκα, πᾶσαι, ἀγαυαί, πᾶσαι]","{('ἄλλος', 'ADJ'): 1, ('ἕπομαι', 'VERB'): 1, (...",πᾶς,ADJ
208,01_0033d,1,33,"[ἄλλαι, ἕποντο, δυώδεκα, πᾶσαι, ἀγαυαί, πᾶσαι,...","{('ἄλλος', 'ADJ'): 1, ('ἕπομαι', 'VERB'): 1, (...",πᾶς,ADJ
209,01_0033e,1,33,"[ἕποντο, δυώδεκα, πᾶσαι, ἀγαυαί, πᾶσαι, ἐελδόμ...","{('ἕπομαι', 'VERB'): 1, ('δώδεκα', 'NUM'): 1, ...",πᾶς,ADJ
210,01_0033f,1,33,"[δυώδεκα, πᾶσαι, ἀγαυαί, πᾶσαι, ἐελδόμεναι, πό...","{('δώδεκα', 'NUM'): 1, ('πᾶς', 'ADJ'): 2, ('ἀγ...",πᾶς,ADJ
211,01_0033g,1,33,"[πᾶσαι, ἀγαυαί, πᾶσαι, ἐελδόμεναι, πόλεμον, ἀε...","{('πᾶς', 'ADJ'): 2, ('ἀγαυός', 'ADJ'): 1, ('ἔλ...",πᾶς,ADJ
...,...,...,...,...,...,...,...
59835,14_0610d,14,610,"[μέσον, ἀνεφαίνετο, κῦμα, ἄλλοι, ἄλλην]","{('μέσος', 'ADJ'): 1, ('ἀναφαίνω', 'VERB'): 1,...",ἄλλος,ADJ
59836,14_0610e,14,610,"[ἀνεφαίνετο, κῦμα, ἄλλοι, ἄλλην, κῆρα]","{('ἀναφαίνω', 'VERB'): 1, ('κῦμα', 'NOUN'): 1,...",ἄλλος,ADJ
59837,14_0610f,14,610,"[ἀνεφαίνετο, κῦμα, ἄλλοι, ἄλλην, κῆρα, κακὴν]","{('ἀναφαίνω', 'VERB'): 1, ('κῦμα', 'NOUN'): 1,...",ἄλλος,ADJ
59838,14_0610g,14,610,"[κῦμα, ἄλλοι, ἄλλην, κῆρα, κακὴν, λάχον]","{('κῦμα', 'NOUN'): 1, ('ἄλλος', 'ADJ'): 2, ('κ...",ἄλλος,ADJ
59839,14_0611a,14,611,"[ἄλλοι, ἄλλην, κῆρα, κακὴν, λάχον]","{('ἄλλος', 'ADJ'): 2, ('κήρ', 'NOUN'): 1, ('κα...",ἄλλος,ADJ

Exclude rows with repetitions (two identical tokens instead of two different forms of the same lemma)

In [15]:
def exclude_repetitions(tokens_list):
    duplicates = set()
    for token in tokens_list:
        if token in duplicates:
            return True
        duplicates.add(token)
    return False

# Filter out rows where the 'tokens' list contains duplicate forms
noreps_expanded_results = expanded_results[~expanded_results['tokens'].apply(exclude_repetitions)].copy()

display(noreps_expanded_results)

,window_id,book,line,tokens,wc,rep_lemma,rep_pos
1485,01_0224f,1,224,"[βοείας, κόρυθας, βριαράς, ἕτερος, ἑτέρου]","{('βοείη', 'ADJ'): 1, ('κόρυς', 'NOUN'): 1, ('...",ἕτερος,ADJ
1486,01_0225a,1,225,"[κόρυθας, βριαράς, ἕτερος, ἑτέρου, χρόα]","{('κόρυς', 'NOUN'): 1, ('βριαρός', 'ADJ'): 1, ...",ἕτερος,ADJ
1487,01_0225b,1,225,"[κόρυθας, βριαράς, ἕτερος, ἑτέρου, χρόα, χαλκῷ]","{('κόρυς', 'NOUN'): 1, ('βριαρός', 'ADJ'): 1, ...",ἕτερος,ADJ
1488,01_0225c,1,225,"[βριαράς, ἕτερος, ἑτέρου, χρόα, χαλκῷ, τύπτον]","{('βριαρός', 'ADJ'): 1, ('ἕτερος', 'ADJ'): 2, ...",ἕτερος,ADJ
1489,01_0225d,1,225,"[ἕτερος, ἑτέρου, χρόα, χαλκῷ, τύπτον]","{('ἕτερος', 'ADJ'): 2, ('χρώς', 'NOUN'): 1, ('...",ἕτερος,ADJ
...,...,...,...,...,...,...,...
59835,14_0610d,14,610,"[μέσον, ἀνεφαίνετο, κῦμα, ἄλλοι, ἄλλην]","{('μέσος', 'ADJ'): 1, ('ἀναφαίνω', 'VERB'): 1,...",ἄλλος,ADJ
59836,14_0610e,14,610,"[ἀνεφαίνετο, κῦμα, ἄλλοι, ἄλλην, κῆρα]","{('ἀναφαίνω', 'VERB'): 1, ('κῦμα', 'NOUN'): 1,...",ἄλλος,ADJ
59837,14_0610f,14,610,"[ἀνεφαίνετο, κῦμα, ἄλλοι, ἄλλην, κῆρα, κακὴν]","{('ἀναφαίνω', 'VERB'): 1, ('κῦμα', 'NOUN'): 1,...",ἄλλος,ADJ
59838,14_0610g,14,610,"[κῦμα, ἄλλοι, ἄλλην, κῆρα, κακὴν, λάχον]","{('κῦμα', 'NOUN'): 1, ('ἄλλος', 'ADJ'): 2, ('κ...",ἄλλος,ADJ
59839,14_0611a,14,611,"[ἄλλοι, ἄλλην, κῆρα, κακὴν, λάχον]","{('ἄλλος', 'ADJ'): 2, ('κήρ', 'NOUN'): 1, ('κα...",ἄλλος,ADJ

In [16]:
noreps_expanded_results.to_csv('ph_pol_noreps_7win_12_3_26.csv')